### ISSUE TITLE
Problem: Connect/Become user issue

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/ansible-webui-v0#1]
### Versions

Ansible Web-UI	latest
Django	4.2.10
Django Rest-Framework	3.14.0
Gunicorn	21.2.0
Ansible Core	ansible [core 2.15.9]
Ansible Runner	2.3.5

### Scope

Ansible (Job Execution)

### Issue

The target server logs: `sshd: Invalid user ansible-webui`
It seems the `ansible_user` variable is not set/used in a consistent manner.
If I create credentials - they work for a few runs. But they stop working after some time.

As a workaround I added `-e ansible_user=<USER>` as 'Commandline Arguments' of the job.

**Also:**
It seems if I do not set a specific become-user it defaults to the connect-user - which is not the expected/default behavior: (should be root)
 `-u <USER> --become-user <USER> `
See: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#become-directives

**Comment by ansibleguy** [comment]
Become-user is now set to 'root' by default.
I was not able to find any issue with the `connect-user` handling. Maybe some config in your environment is overruling the commandline args?
