### ISSUE TITLE
Feature: Settings for gunicorn SSL

### ISSUE THREAD

**Issue by zyndok** [O-X-L/ansible-webui-v0#14]
### Scope

Unknown

### Description

I have not installed the new ansibleguy-webui, but I've been following progress.  I was also following the lack of progress on Semaphore.  Thank you for your efforts on this.  The demo site is down right now, but I'm planning to install.

Now onto my feature request, I would like native support for SSL certificates, particularly those from Lets Encrypt, but specific support is not essential.

A similar request fell on tone deaf ears in Semaphore.  Hoping it evolves here.  I don't use containers.

Thanks for the consideration.  No scope fits this request, so leaving it Unknown.

**Comment by ansibleguy** [comment]
Greetings @zyndok 
I am working as an IT-systems engineer and in my experience it is common practice that web-applications require a proxy (like nginx) to handle SSL termination and security filtering.

Even the gunicorn webserver, which is used by this project, recommends such a setup in its documentation: https://docs.gunicorn.org/en/stable/deploy.html#deploying-gunicorn

What I could offer: Adding settings to provide a SSL keypair to the gunicorn webserver.
That way you would be able to run it with SSL if the keys exist on your machine. Letsencrypt handling will need to be done externally by some tool like [certbot](https://certbot.eff.org/).
But I would not recommend to not use a proxy if the application is facing the/a public network.

BTW: My monitoring has not shown any problems with the [demo.webui.ansibleguy.net](https://demo.webui.ansibleguy.net) page. Could you tell me what error you are seeing? Would be interesting

**Comment by ansibleguy** [comment]
SSL key/cert file can be provided in the next release
Docs: https://webui.ansibleguy.net/en/latest/usage/4_config.html#only-env

**Comment by zyndok** [comment]
Thank you for the responsive support regarding https.

Website issue(s) most likely arose from using UBO in medium modem and/or user.js.  Cloudflare was not on the javascript allow list.

**Comment by ansibleguy** [comment]
FYI: The `AW_LISTEN` is now available to allow to change the listen-address
