### ISSUE TITLE
Feature: ansible role to deploy

### ISSUE THREAD

**Issue by zyndok** [O-X-L/ansible-webui-v0#20]
### Scope

Unknown

### Description

I'm an anxiously awaiting your ansible role to cleanly install ag-webui.  I'd expect this to be a low priority.

Off to do my first install.  Expect more "Issues"!

Side bar; probably due to UBO medium mode and/or user.js on firefox, the checkboxes for Docs and Ansible Docs are not not clickable.

**Comment by ansibleguy** [comment]
Greetings!

Here's the first draft of the role: https://github.com/ansibleguy/sw_ansible_webui
Note: I did not yet have the time to test it as molecule bugged-out - so it might still a bit buggy.

**Comment by ansibleguy** [comment]
Is now tested
