### ISSUE TITLE
Problem: Git-Repository - host-key verification

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/ansible-webui-v0#22]
### Versions

0.0.15

### Scope

Service (Job Scheduling, Job Preparation)

### Issue

The git cloning is not using the configured `known_hosts` file.
The `Git Override Initialize-Command` should be documented with some examples.

```bash
Got error: 'Cloning into '/tmp/ansible-webui/repositories/TEST'...
Host key verification failed.
fatal: Could not read from remote repository.
```

**Comment by ansibleguy** [comment]
Should be fixed. Please report back if it still does not work in the next version
