### ISSUE TITLE
Feature: Execution Forms

### ISSUE THREAD

**Issue by superstes** [O-X-L/ansible-webui-v0#29]
### Scope

Frontend (User Interface)

### Description

Sometimes users want/need to executes jobs with some override or a job is always meant to be ran with some given variables (pe. create user X with privilege Y on server Z)

**Comment by ansibleguy** [comment]
We could use the existing spoiler on the job-manage UI for that use-case.
The current one is pretty useless in my opinion. We could compress the brief result of the last 10 runs into 2 lines inside that spoiler

**Comment by ansibleguy** [comment]
Implemented via https://github.com/ansibleguy/webui/commit/f89fc642732fd7ebc76e1325ff03178179bdd226
