### ISSUE TITLE
Problem: Staff-user/Manager Permission Access

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/ansible-webui-v0#3]
### Versions

Ansible Web-UI	latest
Django	4.2.10
Django Rest-Framework	3.14.0
Gunicorn	21.2.0
Ansible Core	ansible [core 2.15.9]
Ansible Runner	2.3.5

### Scope

Backend (API)

### Issue

Manager users marked as `staff` are able to change permissions they that limit their own access.
They are able to add permissions to grant themselves higher privileges

**Comment by NiceRath** [comment]
Possible fix: Split-Up job-manager and permission-manager privileges.
Job-manager is needed in most cases

**Comment by ansibleguy** [comment]
Should be fixed
