### ISSUE TITLE
Feature: create more type of forms

### ISSUE THREAD

**Issue by vampywiz17** [O-X-L/ansible-webui-v0#51]
### Scope

Frontend (User Interface)

### Description

It would be good to use other type of variable, for example drop down menu, etc...

**Comment by ansibleguy** [comment]
Greetings!

Makes sense - yes.

Just to clarify: you are talking about the [custom execution](https://webui.ansibleguy.net/en/latest/usage/jobs.html#execute), yes?
![image](https://github.com/user-attachments/assets/81fe39f3-6f63-41d6-a187-e8ab5d8d9200)

If we use the current format we could use something like that:
`var_choice=action_type#Action to perform#add,update,delete`

Which would create a dropdown with:
* Title: `Action to perform`
* Set variable: `action_type`
* Dropdown choices: `add`, `update` and `delete`

What do you think?

**Comment by vampywiz17** [comment]
@ansibleguy 

yes, talking about custom execution.

It seems good yes! 

Or also think that would be good to define the type of variables... for example string, number, password, url, etc... and in interface, only accept these type of values.

similar with suse manager salt formulas editor:

https://documentation.suse.com/suma/4.3/en/suse-manager/specialized-guides/salt/salt-formulas-custom.html

**Comment by ansibleguy** [comment]
What do you think of that approach?
I think a regex is easy to implement and can empower users to validate their data as needed.

![image](https://github.com/user-attachments/assets/cd8ea004-4b84-4cb3-a57f-6353ff97e2d0)
![image](https://github.com/user-attachments/assets/53e2d902-b588-4134-bacb-7a4301abbe79)

**Comment by vampywiz17** [comment]
Yes it seems really good!

**Comment by ansibleguy** [comment]
Would be nice if you could give some feedback on the feature: https://github.com/ansibleguy/webui/releases/tag/0.0.22-2

**Comment by vampywiz17** [comment]
@ansibleguy 
Hi, i tested it. the choose option are worrking well ! the new way of config are also good. but regex i think some problem. I try to setup a variable, that only accept email. i use these regex but seems it accept every string:

https://regex101.com/r/gZ0aQ7/1

**Comment by vampywiz17** [comment]
@ansibleguy

Hi, I tested it. the option works well! the new configuration mode is also good. ~~but I think the regex is a problem. I'm trying to set a variable that only receives email. I'm using these regexes, but it seems to accept any string:~~

https://regex101.com/r/gZ0aQ7/1

I use a wrong regex, now it working well :)

**Comment by vampywiz17** [comment]
What do you think the grouping? For example:

![image](https://github.com/user-attachments/assets/fd10a0b9-ca97-46f7-949c-651fd2d719bb)

**Comment by ansibleguy** [comment]
Yeah. Will give it a shot when I find time (:
