### ISSUE TITLE
Feature: Separate Playbook and Inventory folder

### ISSUE THREAD

**Issue by vampywiz17** [O-X-L/ansible-webui-v0#52]
### Scope

Service (Job Scheduling, Job Preparation)

### Description

It would be good to add possibility to separate playbook/inventory folder.

For example, i add my gitlab repo to use, and my folder structure is 

- Playbook
- Inventory

If i add "Playbook" folder to "Git Playbook Base-Directory" on UI, i can not see my Inventory files. 

My idea:

add a new config option on repo field name: "Git Inventory Base-Directory" if these field are empty, it automatically use playbook directory, if filled, use different directory.

**Comment by ansibleguy** [comment]
Greetings.

With `can not see my Inventory files` you mean they don't show up in the browsing-mode, yes?

As Ansible has [a pretty clear guidelines when it comes to the directory-layout](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout) I personally don't really see a need for a change like that.
And we had some issues with path-traversal - so `../` is blocked for security reasons.

A setup like this will work and follow the guidelines:
```
.
├── inventories
│   ├── dev
│   │   └── hosts.yml
│   └── production
│       └── hosts.yml
├── playbook1.yml
├── playbook2.yml
└── playbook3.yml
```

Of course if you have many playbooks, this can get messy. But I see this as an Issue of Ansible itself..

**Comment by vampywiz17** [comment]
I see. Ok i follow the official way thanks. :) It working :)
