### ISSUE TITLE
Problem: fontawesomefree and admin resources not available?

### ISSUE THREAD

**Issue by mathieumd** [O-X-L/ansible-webui-v0#57]
### Versions

Python 	3.10.12
AnsibleGuy WebUI 	0.0.23.post3
AW Database Schema 	0.0.23.post3 (updated: 2024-09-12 14:39:03)
Django 	5.0.9
Django Rest-Framework 	3.15.2
Gunicorn 	23.0.0
Ansible Core 	ansible [core 2.17.4]
Ansible Runner 	2.4.0
Ansible Playbook 	/home/ansibleguy-webui/venv/bin/ansible-playbook
Jinja 	3.1.4
Git 	git version 2.34.1
Running User 	ansibleguy-webui

### Scope

Frontend (User Interface)

### Issue

There are requests to `/static/fontawesomefree/js/fontawesome.js` (and `solid.css` and `brands.js`) which are not found. It looks like it hides text of buttons (aquablue, green, etc.).

And in the admin interface, all resources are requested under `/static/admin/`, (for example `/static/admin/js/nav_sidebar.js`), which are not found either. The admin interface is then unusable.

**Comment by ansibleguy** [comment]
Greetings.

Can you try to un- and reinstall it? (or install it in a new venv and check if the error has gone?)

I just tested it using a clean new venv using the pip-install and everything, including the admin-ui, looks good.
```bash
python3 -m virtualenv /tmp/test
source /tmp/test/bin/activate
pip install ansibleguy-webui
python3 -m ansibleguy-webui
```

![image](https://github.com/user-attachments/assets/66f6f66e-b989-4547-98d4-252faba61636)

**Comment by ansibleguy** [comment]
Maybe also try STRG+SHIFT+F5 to clean your browser cache for this website.
Could be that the Content-Security-Policy and some cached content is the cause

**Comment by mathieumd** [comment]
Hello!

I found the problem: the [example for Nginx](https://github.com/ansibleguy/webui/blob/latest/examples/nginx.conf) only talks about AW resources:

```ngin
  location ~ ^/static/ {
    root <PATH-TO-VENV>/ansibleguy-webui/aw/;  // p.e. /home/ansible-webui/venv/lib/python3.11/site-packages/ansibleguy-webui/aw/
    try_files $uri =404;
  }
```

But it's missing FontAwesome and Django's! This snippet is working well (in that order):

```nginx
        location ~ ^/static/admin/ {
                root /home/ansibleguy-webui/venv/lib/python3.10/site-packages/django/contrib/admin/;
                try_files $uri =404;
        }
        location ~ ^/static/fontawesomefree/ {
                root /home/ansibleguy-webui/venv/lib/python3.10/site-packages/fontawesomefree/;
                try_files $uri =404;
        }
        location ~ ^/static/ {
                root /home/ansibleguy-webui/venv/lib/python3.10/site-packages/ansibleguy-webui/aw/;
                try_files $uri =404;
        }
```

**Comment by ansibleguy** [comment]
Nice catch! 👍🏼
