### ISSUE TITLE
Problem: SQLite Write Lock

### ISSUE THREAD

**Issue by ansibleguy** [O-X-L/ansible-webui-v0#6]
### Versions

latest

### Scope

Backend (API)

### Issue

Since implementing the repository functionality we randomly see `OperationalError: database is locked` errors occurring.
It looks like some write operation locks the database for multiple seconds.
SQLite only supports one write-operation at a time. This is a known limitation.
We should not run into that limitation for some time. The writes we perform are not data-intensive and should easily be done in < 0.1s

**Comment by ansibleguy** [comment]
Seems there was a recent change that could help with that behavior: https://github.com/django/django/commit/a0204ac183ad6bca71707676d994d5888cf966aa (but it can still take some time until that becomes available)

The root issue is described in the ticket: https://code.djangoproject.com/ticket/29280

**Comment by ansibleguy** [comment]
Probably resolved for now. Will re-open if recurring

**Comment by NiceRath** [comment]
Had this one over night - the whole service was essentially stuck.
As a workaround: Maybe have one thread check for this issue and fail/restart the service if stuck?
