### ISSUE TITLE
Feature: Way to stop following ansible output

### ISSUE THREAD

**Issue by mathieumd** [O-X-L/ansible-webui-v0#63]
### Scope

Frontend (User Interface)

### Description

When you click the ["Show Logs" button](https://fontawesome.com/v5/icons/angle-double-down?f=classic&s=regular) to watch Ansible output of a job, it's quite hard to close it back, as it's always moving/resizing its frame.

Maybe making it a little less high, to make sure the ["Collapse"](https://fontawesome.com/v5/icons/angle-double-up?f=classic&s=regular) and ["Stop Execution"](https://fontawesome.com/v4/icon/stop-circle) buttons are always visible, could be a solution. And/or to use the Escape key to close the frame, too?

**Comment by mathieumd** [comment]
Also, it would be nice to be able to scroll up the logs even if the job is not yet terminated. Currently, you can scroll a bit, but you are quickly put back at the bottom of the log. Frustrating! :laughing:

**Comment by ansibleguy** [comment]
1. Have moved the target for the scrolling down a bit, so we can see the buttons
2. We now have a refresh toggle-button
  ![image](https://github.com/user-attachments/assets/b93f6815-c8d8-49da-9fe5-e15ecbbb4938)

**Comment by mathieumd** [comment]
I refresh my browser cache, but I'm still getting the buttons under the footer:
![2024-09-18_11-44](https://github.com/user-attachments/assets/338a40b7-9bba-4249-86e5-85270a6cc783)

So I couldn't either test the Stop Scroll button, as it's constantly moving (which it's not when it's `pause`, of course :wink: ).

**Comment by superstes** [comment]
Please try it in a private tab. Maybe something was cached.
Which browser do you use?

**Comment by mathieumd** [comment]
Firefox (v130.0), of course ;-)

1. Buttons are still hidden behind the footer in a private window.
2. I think I successfully clicked the (top of the) Stop Scroll button, but the scroll didn't stop.

**Comment by ansibleguy** [comment]
Ok. Have tried it with chromium and firefox.
Is not refactored a bit:
![image](https://github.com/user-attachments/assets/95fda06e-42f9-476b-92bf-2357c43f794c)

The buttons are now fixed (always hover above the output)

**Comment by mathieumd** [comment]
Oh, I'm sorry, it was my Nginx rewrite of `/static/` which was still targeting the PyPI version...

It's working well.

I would add some CSS to move the buttons above other job's:
```css
.aw-execution-logs-footer {
  position: fixed;
  bottom: 60px;
  right: 5vw;
  /*padding-left: 20px;*/
/* Adding something like that: */
  z-index: 9;
  background-color: white;
  padding: 5px 10px;
  border: 1px solid;
}
```
![Screenshot_20240919_134023](https://github.com/user-attachments/assets/e7173c78-c1f2-4c89-b4a2-aecfcf664b40)
Instead of:
![Screenshot_20240919_134341](https://github.com/user-attachments/assets/ac0d8d01-85a3-4a86-bc91-a08ba3e42bcf)

**Comment by ansibleguy** [comment]
Yeah.

Just tried 1h to get the damn buttons to vanish once they overflow the logs-container.. but no luck.
The 'fixed' position seems to be 'very special'. Not even 'z-index' is working.
CSS work really is not my favorite....

The only workaround I could think of, is using JS to check if the buttons overlap the logs-container and hide them if they are over or under the 'parent' container. But that's far from a 'clean' solution.

**Comment by ansibleguy** [comment]
Edit: Got it at last.. Buttons only shown inside the logs-container
![image](https://github.com/user-attachments/assets/ba117abe-0824-4f8c-90d6-ba27359236a0)
