### ISSUE TITLE
Problem: Django Groups "AW * Managers" have no permissions?

### ISSUE THREAD

**Issue by mathieumd** [O-X-L/ansible-webui-v0#64]
### Versions

0.0.23.post3

### Scope

Frontend (User Interface)

### Issue

In the *Admin > Groups*, all the `AW * Managers` groups have nothing in *Chosen permissions*.

I suppose they should have a pre-selection of permissions; but they are all empty.

A group I created by myself does display the chosen permissions, so it's maybe a bug during installation?

**Comment by mathieumd** [comment]
Oh, my bad. These are not Django permissions, but AW ones, and they are hard-coded in the app, right?

Maybe they should appear (even as read-only) in *Settings > Permissions* for admin users?

**Comment by ansibleguy** [comment]
Yeah - I have not used the Django permission system.
It's understandable that this is a little confusing.

In my opinion the docs explain it good-enough: https://webui.ansibleguy.net/en/latest/usage/privileges.html#managers
