### ISSUE TITLE
Problem: Displaying of job log file freezes for 5 seconds

### ISSUE THREAD

**Issue by mathieumd** [O-X-L/ansible-webui-v0#67]
### Versions

d610082c25f2dc812344544d991ed856e381cb0e

### Scope

Frontend (User Interface)

### Issue

Since I pull'ed the `main` branch (instead of PyPI's version), the displaying of any job log file freezes the window (and the mouse cursor) for about 5s on this:

> **Start time**: 2024-09-23 11:12:00 Europe/Paris
> **Running command:**
> ansible-playbook --diff -i inventory/all --limit test01 playbooks/test.yml
> 
> Finish time: 2024-09-23 11:12:37 Europe/Paris
> Duration: 35s

Then it unfreezes and eventually include the log file (between the `ansible-playbook` and the `Finish time` lines).

I did not noticed such freeze on PyPI's version.

**Comment by superstes** [comment]
Have seen that too.
Should be fixed after this commit: https://github.com/ansibleguy/webui/commit/6a741531db06f7eb7edd0680754e2a6dbd0ee86c

**Comment by ansibleguy** [comment]
Yeah - should be fixed

**Comment by mathieumd** [comment]
Yes, thank you!
