### ISSUE TITLE
Problem: Jobs stuck on SSH-Password-Prompt

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/ansible-webui-v0#70]
### Versions

0.0.24

### Scope

Ansible (Job Execution)

### Issue

Jobs are stuck on the prompt `SSH password: ` - the other ones work as expected

**Comment by NiceRath** [comment]
The code looks good: https://github.com/ansibleguy/webui/blob/latest/src/ansibleguy-webui/aw/execute/play_credentials.py#L108

**Comment by moy804** [comment]
I'm seeing the same.  The jobs are stuck but from the Running command: output there doesn't seem to be a user or credentials passed in:

![Capture](https://github.com/user-attachments/assets/6c848c9b-59d5-4019-83ff-a53f7fc19701)

**Comment by superstes** [comment]
Possible issue with the formatting? Needs to be regex?
https://github.com/ansible/ansible-runner/issues/534

**Comment by ansibleguy** [comment]
Yes - looks like it wants regex: https://github.com/ansible/ansible-runner/blob/devel/src/ansible_runner/config/_base.py#L199

**Comment by ansibleguy** [comment]
Seems it makes no difference if we supply the matches in regex format..
Debugging shows that the ansible-runner actually sends the password, but still nothing happens. At this point in the code the SSH password is sent: https://github.com/ansible/ansible-runner/blob/2.4.0/src/ansible_runner/runner.py#L321

**Comment by ansibleguy** [comment]
Was able to get it working by forking and hotfixing the ansible-runner: https://github.com/ansibleguy/ansible-runner/blob/release_2.4/src/ansibleguy_runner/runner.py#L323
Will create an issue at the ansible-runner repo.. for now we have a fork that should work: https://pypi.org/project/ansibleguy-runner/

**Comment by ansibleguy** [comment]
Related: https://github.com/ansibleguy/webui/issues/72

**Comment by ansibleguy** [comment]
My tests look good.
Please update to the new version an re-test it.

**Comment by moy804** [comment]
I just tried 0.0.24-2 via docker but it doesn't seem to pass the user or credentials to the ansible-playbook statement:
![image](https://github.com/user-attachments/assets/e92a6268-46bb-4b54-8cf4-82121cbad467)

Here's the same playbook output on 0.0.23-3:
![image](https://github.com/user-attachments/assets/292f00f8-e19e-4ee1-a8c6-423cb84ba91e)

**Comment by ansibleguy** [comment]
Very interesting as the `--become-password-file` and `--connect-password-file` are not in the codebase anymore.
Can only think of a issue when building the docker images.. Will check it

**Comment by ansibleguy** [comment]
Have forgot to release the 0.0.24-3 image that has the missing-user fix in it.
Currently uploading..

But also on 0.0.24-2 I was not able to reproduce the behavior seen in your screenshot:
`docker run -d --name ansible-webui --publish 127.0.0.1:8000:8000 --volume $(pwd):/play ansible0guy/webui:0.0.24-2`
![image](https://github.com/user-attachments/assets/d6255914-a7b7-4741-9b99-0732fe8ae249)

**Comment by ansibleguy** [comment]
And with 0.0.24-3 in docker now:
![image](https://github.com/user-attachments/assets/18e36a09-f4c5-4689-a8b3-5cdbef8fe1c4)

**Comment by moy804** [comment]
Looks good to me too.  Much appreciated!
